name: Publish to JSR

on:
  push:
    tags:
      - 'v*.*' # Dispara apenas para tags iniciando com 'v' (ex: v0.2, v1.0.0)
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # Required for JSR OIDC authentication

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions
          cache: true
        
      - name: Install dependencies
        run: deno ci

      - name: Sanitize Version
        run: |
          sh ./sanitize-version.sh ./packages/worker-db/deno.jsonc
          sh ./sanitize-version.sh ./packages/service-worker/deno.jsonc

      - name: Publish WorkerDB to JSR
        run: |
          cd packages/worker-db
          deno publish --allow-slow-types --allow-dirty

      - name: Publish OPFS Explorer to JSR
        run: |
          cd packages/service-worker
          deno publish --allow-slow-types --allow-dirty
